name: Build and Push ECR Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  build-and-push:
    name: Build and Push ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Debugging Secrets and Variables
        run: |
          echo "AWS Access Key ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS Secret Access Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS Region: ${{ secrets.AWS_REGION }}"
          echo "ECR Repository URI: ${{ secrets.ECR_REPOSITORY_URI }}"

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          echo "ECR Repository URI: ${{ secrets.ECR_REPOSITORY_URI }}"
        
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest .

      - name: Push Docker Image to Amazon ECR
        run: |
          echo "Pushing Docker image..."
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest
